server:
  port: 8080

spring:
  application:
    name: stock-webapp
    
  datasource: 
    url: jdbc:mysql://192.168.99.100:3306/stock?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: stock
    password: Aa123456
    driver-class-name: com.mysql.jdbc.Driver
        
  thymeleaf:
    cache: false
  
  # Redis Config  
  redis: 
    host: 192.168.100.88
    port: 6380

mybatis:
  mapperLocations: classpath:mybatis/*.xml

#攔截器需排除的路徑
interceptor: 
  excludePath: |
    /login,
    /loginPage,
    /logout,
    /sessionLostError,
    /fetch/index
  
# Log
logging:
  level:
    root: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} Line:%L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  file: /works/log/stock-webapp/stock-webapp.log
