# linux开发环境
spring:
#  profiles: docker
      
#  zipkin:
#    enabled: true
#    base-url: http://zipkin-server:9411/

  sleuth:
    stream:
      enabled: true
  
  rabbitmq:
    host: 192.168.100.88
    port: 5672
    username: guest
    password: guest
#    virtual-host: cloud_host
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

# Log
logging:
  level:
    root: INFO
  file: /works/log/hkcash/employee-server/employee-server.log
