server:
  port: 8081

spring:
  application:
    name: stock-webapp
    
  datasource: 
    url: jdbc:mysql://192.168.99.100:3306/wenchun?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: wenchun
    password: Aa123456
    driver-class-name: com.mysql.jdbc.Driver
        
  # 这个开发配置为false，避免改了模板还要重启服务器
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: LEGACYHTML5
    
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    time-zone: UTC

  # Redis Config  
  redis: 
    host: 192.168.99.100
    port: 6379

mybatis:
  mapperLocations: classpath:mybatis/*.xml

#攔截器需排除的路徑
interceptor: 
  excludePath: |
    /,
    /login,
    /loginPage,
    /logout,
    /sessionLostError,
    /fetch/index,
    /fetch/index2,
    /fetch/data
  
# Log
logging:
  level:
    root: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} Line:%L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  file: /works/log/stock-webapp/stock-webapp.log
