server:
  port: 8082
  # Session timeout in seconds.
  session:
    # 24h
    timeout: 86400

#攔截器需排除的路徑
interceptor: 
  excludePath: /api/login
  
spring:
  application:
    name: stock-webapp
    
  datasource: 
    url: jdbc:mysql://192.168.99.100:3306/wenchun?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: wenchun
    password: Aa123456
    driver-class-name: com.mysql.jdbc.Driver
        
  # 这个开发配置为false，避免改了模板还要重启服务器
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: LEGACYHTML5

  # Redis Config  
  redis: 
    host: 192.168.99.100
    port: 6379

mybatis:
  mapperLocations: classpath:mybatis/*.xml
  config-location: classpath:mybatis-config.xml
  
stock:
  upload-temp-folder: /temp

# Log
logging:
  level:
    root: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} Line:%L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  file: /works/log/stock-webapp/stock-webapp.log

---
spring:
  profiles: prod
  
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/wenchun?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: Aa654321
    driver-class-name: com.mysql.jdbc.Driver
